src/Entity/Config.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * Config
 *
 * @ORM\Table(name="config")
 * @ORM\Entity
 */
class Config
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="nom_config", type="string", length=50, nullable=false)
     */
    private $nomConfig;

    /**
     * @var string
     *
     * @ORM\Column(name="reference_config", type="string", length=255, nullable=false)
     */
    private $referenceConfig;

    /**
     * @var string
     *
     * @ORM\Column(name="description_config", type="string", length=255, nullable=false)
     */
    private $descriptionConfig;

    /**
     * @var int
     *
     * @ORM\Column(name="remise_config", type="integer", nullable=true)
     */
    private $remiseConfig;

    /**
     * @ORM\OneToMany(targetEntity=EntityPDF::class, mappedBy="Config")
     */
    private $ConfigPDF;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="ConfigUser", cascade={"persist"})
     */
    private $User;

    /**
     * @ORM\Column(type="date")
     */
    private $DateConfig;

    public function __construct()
    {
        $this->ConfigPDF = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomConfig(): ?string
    {
        return $this->nomConfig;
    }

    public function setNomConfig(string $nomConfig): self
    {
        $this->nomConfig = $nomConfig;

        return $this;
    }

    public function getReferenceConfig(): ?string
    {
        return $this->referenceConfig;
    }

    public function setReferenceConfig(string $referenceConfig): self
    {
        $this->referenceConfig = $referenceConfig;

        return $this;
    }

    public function getDescriptionConfig(): ?string
    {
        return $this->descriptionConfig;
    }

    public function setDescriptionConfig(string $descriptionConfig): self
    {
        $this->descriptionConfig = $descriptionConfig;

        return $this;
    }

    public function getRemiseConfig(): ?int
    {
        return $this->remiseConfig;
    }

    public function setRemiseConfig(int $remiseConfig): self
    {
        $this->remiseConfig = $remiseConfig;

        return $this;
    }

    /**
     * @return Collection|EntityPDF[]
     */
    public function getConfigPDF(): Collection
    {
        return $this->ConfigPDF;
    }

    public function addConfigPDF(EntityPDF $configPDF): self
    {
        if (!$this->ConfigPDF->contains($configPDF)) {
            $this->ConfigPDF[] = $configPDF;
            $configPDF->setConfig($this);
        }

        return $this;
    }

    public function removeConfigPDF(EntityPDF $configPDF): self
    {
        if ($this->ConfigPDF->removeElement($configPDF)) {
            // set the owning side to null (unless already changed)
            if ($configPDF->getConfig() === $this) {
                $configPDF->setConfig(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getDateConfig(): ?\DateTimeInterface
    {
        return $this->DateConfig;
    }

    public function setDateConfig(\DateTimeInterface $DateConfig): self
    {
        $this->DateConfig = $DateConfig;

        return $this;
    }


}

templates/AccessoireAjout.html.twig
{% extends 'base.html.twig' %}


{% block title %}Choisir des accessoires{% endblock %}

{% block body %}


<div class="container">
        <div class="w-75 mx-auto">
        <div><h1>Choix des Accessoires</h1></div>
    {{ form_start(Form) }}
    <table>
            <tr>
                <td>
                    <ul class="accessories" data-prototype="{{ form_widget(Form.EchelleAccessoire.vars.prototype)|e('html_attr') }}">
                        {% for accessory in Form.EchelleAccessoire %}
                            <li>
                                <table>
                                    <tr>
                                        <td>{{ form_label(accessory.Accessoire) }}</td>
                                        <td>{{ form_widget(accessory.Accessoire) }}</td>
                                        <td>{{ form_errors(accessory.Accessoire) }}</td>
                                    <tr>
                                    <tr>
                                        <td>{{ form_label(accessory.Qte) }}</td>
                                        <td>{{ form_widget(accessory.Qte) }}</td>
                                        <td>{{ form_errors(accessory.Qte) }}</td>
                                    <tr>
                                </table>
                            </li>
                        {% endfor %}
                    </ul>
                </td>
            </tr>
            <tr>
                <td><button class="text-dark btn bg-warning" type="submit">Suivant</button></td>
                <td><button type="button" class="add_item_link text-dark btn bg-warning" data-collection-holder-class="accessories">+</button></td>
            </tr>
        </table>
    {{ form_end(Form) }}

    
    
        </div>
    </div>

{% endblock %}

{% block javascripts %}
    <script>
        $(document).ready(function() {
            const $accessoriessCollectionHolder = $('ul.accessories');
            $accessoriessCollectionHolder.data('index', $accessoriessCollectionHolder.find('input').length);
            $('body').on('click', '.add_item_link', function(e) {
                var $accessoriessCollectionHolder = $(e.currentTarget).data('collectionHolderClass');
                addFormToCollection($accessoriessCollectionHolder);
            });
            $accessoriessCollectionHolder.find('li').each(function() {
                addTagFormDeleteLink($(this));
            });
        });
        function addFormToCollection($collectionHolderClass) {
            const $collectionHolder = $('.' + $collectionHolderClass);
            const prototype = $collectionHolder.data('prototype');
            const index = $collectionHolder.data('index');
            let newForm = prototype;
            newForm = newForm.replace(/__name__/g, index);
            $collectionHolder.data('index', index + 1);
            const $newFormLi = $('<li></li>').append(newForm);
            $collectionHolder.append($newFormLi);
            addTagFormDeleteLink($newFormLi);
        }
        function addTagFormDeleteLink($accessoryFormLi) {
            const $removeFormButton = $('<button class="text-dark btn bg-warning" type="button">-</button>');
            $accessoryFormLi.append($removeFormButton);
            $removeFormButton.on('click', function() {
                $accessoryFormLi.remove();
            });
        }
    </script>
{% endblock %}

{% block progression %}
{{ include('ProgressionBar.html.twig') }}
{% endblock %}

templates/AjoutFixation.html.twig
{% extends 'base.html.twig' %}


{% block title %}Choisir des accessoires{% endblock %}

{% block body %}


<div class="container">
        <div class="w-75 mx-auto">
        <div><h1>Choix des Fixations</h1></div>
    {{ form_start(Form) }}
    <table>
            <tr>
                <td>
                    <ul class="fixation" data-prototype="{{ form_widget(Form.EchelleFixation.vars.prototype)|e('html_attr') }}">
                        {% for fixation in Form.EchelleFixation %}
                            <li>
                                <table>
                                    <tr>
                                        <td>{{ form_label(fixation.Fixation) }}</td>
                                        <td>{{ form_widget(fixation.Fixation) }}</td>
                                        <td>{{ form_errors(fixation.Fixation) }}</td>
                                    <tr>
                                    <tr>
                                        <td>{{ form_label(fixation.Qte) }}</td>
                                        <td>{{ form_widget(fixation.Qte) }}</td>
                                        <td>{{ form_errors(fixation.Qte) }}</td>
                                    <tr>
                                </table>
                            </li>
                        {% endfor %}
                    </ul>
                </td>
            </tr>
            <tr>
                <td><button class="text-dark btn bg-warning" type="submit">Créer</button></td>
                <td><button type="button" class="add_item_link text-dark btn bg-warning" data-collection-holder-class="fixation">Ajouter Fixation</button></td>
            </tr>
        </table>
    {{ form_end(Form) }}

    
    
        </div>
    </div>

{% endblock %}

{% block javascripts %}
    <script>
        $(document).ready(function() {
            const $fixationsCollectionHolder = $('ul.fixation');
            $fixationsCollectionHolder.data('index', $fixationsCollectionHolder.find('input').length);

            $('body').on('click', '.add_item_link', function(e) {
                var $fixationssCollectionHolder = $(e.currentTarget).data('collectionHolderClass');
                addFormToCollection($fixationssCollectionHolder);
                
            });

            $fixationsCollectionHolder.find('li').each(function() {
                addTagFormDeleteLink($(this));
            });
        });

        function addFormToCollection($collectionHolderClass) {
            const $collectionHolder = $('.' + $collectionHolderClass);
            const prototype = $collectionHolder.data('prototype');
            const index = $collectionHolder.data('index');
            let newForm = prototype;
            newForm = newForm.replace(/__name__/g, index);
            $collectionHolder.data('index', index + 1);
            const $newFormLi = $('<li></li>').append(newForm);
            $collectionHolder.append($newFormLi);
            addTagFormDeleteLink($newFormLi);
        }

        function addTagFormDeleteLink($fixationFormLi) {
            const $removeFormButton = $('<button class="text-dark btn bg-warning" type="button">Delete this Accessory</button>');
            $fixationFormLi.append($removeFormButton);

            $removeFormButton.on('click', function() {
                $fixationFormLi.remove();
            });
        }
    </script>
{% endblock %}
{% block progression %}
{{ include('ProgressionBar.html.twig') }}
{% endblock %}

templates/ChoixNorme.html.twig
{% extends 'base.html.twig' %}

{% block title %}Choisir une Norme{% endblock %}

{% block body %}


<div class="container">
    
        <div class="w-75 mx-auto">
        <div><h1>Choix de la norme</h1></div>
    {{ form_start(NormeAjoutForm) }}
    <table class="table table-striped table-bordered table-sm ">
    {% for key, type in NormeAjoutForm.echelleNorme %}
    {% set attr = NormeAjoutForm.echelleNorme.vars.choices[key].data.ImageUrl %}
    <tr>
      <td>
      {{ form_widget(type) }}
      </td>
    <td style="width:auto"><img src="{{ asset(attr) }}">
    <br>
    {{ NormeAjoutForm.echelleNorme.vars.choices[key].data.descriptionNorme }}</td>
    
     </tr>
    {% endfor %}
   
    </table>
        <a styke="color:black" class="text-dark btn bg-warning" href="{{ path('index') }}">Precedent</a>
        <button class="btn bg-warning">Suivant</button>
    {{ form_end(NormeAjoutForm) }}
    
        </div>
    </div>
<div>
<br>
</div>
<br>
{% endblock %}

{% block progression %}
{{ include('ProgressionBar.html.twig') }}
{% endblock %}

templates/ConfigAjout.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter une configuration{% endblock %}

{% block body %}

    
    <div class="container">
    
        <div class="w-75 mx-auto">
        <div><h1>Ajout d'une configuration</h1></div>
    {{ form_start(ConfigAjoutForm) }}
        {{ form_row(ConfigAjoutForm.NomConfig, {
            label: 'Reference Chantier (Pour le Client)'
        }) }}
        {{ form_row(ConfigAjoutForm.ReferenceConfig, {
            label: 'Reference de la configuration'
        }) }}
        {{ form_row(ConfigAjoutForm.DescriptionConfig, {
            label: 'Description'
        }) }}

        
        <button type="submit" class="btn bg-warning">Suivant</button>
    {{ form_end(ConfigAjoutForm) }}
        </div>
    </div>
{% endblock %}

templates/EntreeAjout.html.twig
{% extends 'base.html.twig' %}

{% block title %}Choisir une Entree{% endblock %}

{% block body %}


<div class="container">
    
        <div class="w-75 mx-auto">
        <div><h1>Choix de l'entrée</h1></div>
    {{ form_start(EntreeAjoutForm) }}
    {# <table class="table table-striped table-bordered table-sm "> #}
    {% for key, type in EntreeAjoutForm.echelleEntree %}
    {# {% set attr = EntreeAjoutForm.echelleEntree.vars.choices[key].data.ImageUrl %} #}
    {# <tr>
      <td> #}
      {{ form_widget(type) }}
      {# </td>
    <td style="width:auto"><img src="{{ asset(attr) }}"></td>
     </tr> #}
    {% endfor %}
   
    {# </table> #}
        <a styke="color:black" class="text-dark btn bg-warning" href="{{ path('index') }}">Precedent</a>
        <button type="submit" class="btn bg-warning">Suivant</button>
    {{ form_end(EntreeAjoutForm) }}
    
        </div>
    </div>
<div>
<br>
</div>
<br>
{% endblock %}

{% block progression %}
{{ include('ProgressionBar.html.twig') }}
{% endblock %}

templates/Formulaire.html.twig
{% block bouton %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>jQuery UI Tabs - Default functionality</title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
  $( function() {
    $( "#tabs" ).tabs();
  } );
  </script>
</head>
<body>




 <div id="tabs" classe="d-flex justify-content-center">
  <ul>
    <li><a href="#tabs-1">Normes</a></li>
    <li><a href="#tabs-2">Hauteur Echelle</a></li>
    <li><a href="#tabs-3">Sortie Echelle</a></li>
    <li><a href="#tabs-4">Sortie Echelle</a></li>
    <li><a href="#tabs-5">Sortie Echelle</a></li>
    <li><a href="#tabs-6">Sortie Echelle</a></li>
    <li><a href="#tabs-7">Sortie Echelle</a></li>
  </ul>


<div class="p-2" id="tabs-1">
    {{ form_start(form) }}
    <div class="form-group">
        {{ form_errors(form) }}
    </div>

    <div class="form-group">
    <div>
            {{ form_label(form.name, 'Hauteur') }}
            {{ form_widget(form.name) }}
    </div>
    <div>
            {{ form_label(form.name, 'Autre Longueur') }}
            {{ form_widget(form.price) }}
        </div>
    </div>
{{ form_end(form) }}
</div>



<div id="tabs-2">
    <p>Onglet de test des Echelles</p>
</div>
<div id="tabs-3">
    <p>Onglet de test des Sorties</p>
</div>
<div class="p-2" id="tabs-4">
<p>Une autre option 1</p>
</div>
<div class="p-2" id="tabs-5">
<p>Une autre option 2</p>
</div>
<div class="p-2" id="tabs-6">
<p>Une autre option 3</p>
</div>
<div class="p-2" id="tabs-7">
<p>Une autre option 4</p>
</div>
</div>
 
</body>
</html>
{% endblock %}

templates/HauteurAjout.html.twig
{% extends 'base.html.twig' %}

{% block title %}Choisir une Hauteur{% endblock %}

{% block body %}


<div class="container">
    
        <div class="w-75 mx-auto">
        <div><h1>Choix de la hauteur</h1></div>
    {{ form_start(HauteurAjoutForm) }}
        {{ form_row(HauteurAjoutForm.AFranchirHauteur, {
            label: 'Hauteur souhaitée'
        }) }}

        <a styke="color:black" class="text-dark btn bg-warning" href="{{ path('index') }}">Precedent</a>
        <button type="submit" class="btn bg-warning">Suivant</button>
    {{ form_end(HauteurAjoutForm) }}
    
        </div>
    </div>
<div>
<br>
</div>
<br>
{% endblock %}

{% block progression %}
{{ include('ProgressionBar.html.twig') }}
{% endblock %}

templates/Index.html.twig
{% extends "base.html.twig" %}


{% block body %}

{% if is_granted('IS_AUTHENTICATED_FULLY') %}
    <p class="text-center">Bonjour ! Votre Email est : {{ app.user.email }}</p>

{% if is_granted('ROLE_USER') and not is_granted('ROLE_ADMIN') %}

    <div class="container">
            <center><h3>Liste des Config</h3></center>
                <!-- Tableau qui affiche les config -->
                <table id="ListeConfig" class="table table-striped table-bordered table-sm ">
                    <thead>
                        <tr>
                            <!-- <th class="bg-warning" style="color:white;">Nom</th> -->
                            <th class="bg-warning" style="color:white;">Nom</th>
                            <th class="bg-warning" style="color:white;">Description</th>
                            <th class="bg-warning" style="color:white;">Reference</th>
                            <th class="bg-warning" style="color:white;">Date</th>
                            <th class="bg-warning" style="color:white;">Actions</th>

                            <!-- <th class="bg-warning" style="color:white;"></th> -->
                        </tr>
                    </thead>
                    <tbody>
                        {% for Config in listeConfig.getConfigUser %}
                            <tr>
                                <td class="table-light"><a href="{{ path('pdf3', {'id': Config.id}) }}">
                                {{ Config.NomConfig }}
                                </a></td>
                                <td class="table-light">{{ Config.DescriptionConfig }}</td>
                                <td class="table-light">{{ Config.ReferenceConfig }}</td>
                                <td class="table-light">{{ Config.DateConfig|date('Y-m-d') }}</td>
                                <td class="table-light"><a class="btn btn-danger btn-sm" onclick="return confirm('Etes-vous sur de vouloir supprimer cette configuration ?')" href="#">Supprimer</a> <a class="btn btn-primary btn-sm" href="#">Modifier</a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            {% endif %}


             {% if is_granted('ROLE_ADMIN') %}
                    <div class="container">
            <center><h3>Liste des Config</h3></center>
                <!-- Tableau qui affiche les config -->
                <table id="ListeConfig" class="table table-striped table-bordered table-sm ">
                    <thead>
                        <tr>
                            <!-- <th class="bg-warning" style="color:white;">Nom</th> -->
                            <th class="bg-warning" style="color:white;">Nom</th>
                            <th class="bg-warning" style="color:white;">Description</th>
                            <th class="bg-warning" style="color:white;">Reference</th>
                            <th class="bg-warning" style="color:white;">Date</th>
                            <th class="bg-warning" style="color:white;">Remise</th>
                            <th class="bg-warning" style="color:white;">Actions</th>

                            <!-- <th class="bg-warning" style="color:white;"></th> -->
                        </tr>
                    </thead>
                    <tbody>
                        {% for Config in listeAdmin %}
                            <tr>
                                <td class="table-light"><a href="{{ path('pdf3', {'id': Config.id}) }}">
                                {{ Config.NomConfig }}
                                </a></td>
                                <td class="table-light">{{ Config.DescriptionConfig }}</td>
                                <td class="table-light">{{ Config.ReferenceConfig }}</td>
                                <td class="table-light">{{ Config.DateConfig|date('Y-m-d') }}</td>
                                <td class="table-light">{% if Config.RemiseConfig is null %} Pas de Remise allouée
                                {% else %}{{ Config.RemiseConfig }} {% endif %}</td>
                                <td class="table-light"><a class="btn btn-danger btn-sm" onclick="return confirm('Etes-vous sur de vouloir supprimer cette configuration ?')" href="#">Supprimer</a> <a class="btn btn-primary btn-sm" href="{{ path('ModifierConfig', { 'id' : Config.id }) }}">Modifier</a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <br>
            <br>
             {% endif %}
{% endif %}

{% endblock %}

templates/ModifierConfig.html copy.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter une configuration{% endblock %}

{% block body %}

    
    <div class="container">
    
        <div class="w-75 mx-auto">
        <div><h1>Ajout d'une configuration</h1></div>
    {{ form_start(ConfigAjoutForm) }}
        {{ form_row(ConfigAjoutForm.NomConfig, {
            label: 'Reference Chantier (Pour le Client)'
        }) }}
        {{ form_row(ConfigAjoutForm.ReferenceConfig, {
            label: 'Reference de la configuration'
        }) }}
        {{ form_row(ConfigAjoutForm.DescriptionConfig, {
            label: 'Description'
        }) }}

        {% if not is_granted('ROLE_ADMIN') %}
        {% do ConfigAjoutForm.RemiseConfig.setRendered() %}
        {% else %}
        {{ form_row(ConfigAjoutForm.RemiseConfig) }}
        {% endif %}


        
        <button type="submit" class="btn bg-warning">Suivant</button>
    {{ form_end(ConfigAjoutForm) }}
        </div>
    </div>
{% endblock %}

templates/Theme.html.twig
{{% block Theme %}}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
 <meta charset="utf-8">
 <meta name="viewport" content="width=device-width, initial-scale=1">

 {# Création du bloc "title" avec "Plateforme" comme contenu par défaut #}
 <title>{% block title %}Configurateur{% endblock %}</title>

 {% block stylesheets %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<link href="sticky-footer.css" rel="stylesheet">

 {% endblock %}

 {% block javascripts %}
 <script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
 {%  endblock %}
</head>
<!-- on définit la couleur de fond -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<ul class="navbar-nav mr-auto">
<li class="nav-item active">
<img class="logo align-top align-middle align-bottom" src="{{ asset('build/img/amihauteur.png') }}" alt="Ami-hauteur logo" style="width=60%; height:auto">
{% if not is_granted('IS_AUTHENTICATED_REMEMBERED') %}
  <a class="navbar-brand" alt"" href=" {{ path('logout') }} ">Accueil</a>
  {% endif %}
  {% if is_granted('IS_AUTHENTICATED_FULLY') %}
  <a class="navbar-brand" href=" {{ path('index') }} ">Accueil</a>
  {% endif %}
  {% if is_granted('IS_AUTHENTICATED_FULLY') %}
  <a class="navbar-brand" href="{{ path('ajout', { 'verification' : 1 }) }}">Ajouter</a>
  {% endif %}
  {% if is_granted('ROLE_ADMIN') %}
     <a class="navbar-brand" href="{{ path('GestionAdmin') }}">Gerer le site (Admin)</a>
{% endif %}
  </li>
  </ul>
  {% if is_granted('IS_AUTHENTICATED_FULLY') %}
  <p style="font-size:1.2em;" class="navbar-brand my-2 my-sm-0 align-top align-middle align-bottom">Bienvenue, <span style="color:red;">{{ app.user.prenom }}</span></p> <a class="navbar-brand my-2 my-sm-0" href="{{ path('logout') }}">Deconnexion</a>
  {% endif %}
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <style>

body
{
  margin-bottom:100px;
}

.btn.bg-warning {
  background-color: #ff7f18 !important;
  color: black;
}
.text-dark,
.btn.bg-warning:active,
.btn.bg-warning:hover,
.btn.bg-warning:focus {
  background-color: #FF5100 !important;
}

.navbar
{
  background-color: #e3e3e3 !important;
  margin-bottom:20px;
}

.logo
{
  
}

footer
{
  background-color:#e3e3e3;
}

.navbar-brand
{
  font-size:1.5em;
}


  </style>



  {# <div class="collapse navbar-collapse" id="navbarSupportedContent"> #}
    {# <ul class="navbar-nav mr-auto"> #}
      {# <li class="nav-item active"> #}

      {# </li> #}
    {# </ul> #}
  {# </div> #}
</nav>
        <!-- Création du bloc "body" sans contenu par défautn-->
        {% block body %}

        {% endblock %}

    {% block progression %}
    {% endblock %}


<footer id="footer" class="footer-1 fixed-bottom">
<div class="footer-copyright">
<div class="container">
<div class="row">
<div class="col-md-12 text-center">
<p>Site developpé par Ami-Hauteur</p>
</div>
</div>
</div>
</div>
</footer>

templates/footer.html.twig
{# <footer id="footer" class="fixed-bottom">
<div class="footer-copyright">
<div class="container">
<div class="row">
<div class="col-md-12 text-center">
<p>Site developpé par Ami-Hauteur</p>
</footer> #}

templates/test2.html.twig
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<style>
img {
	width: auto;
	height: 1200px;
    border-width : 3px;
    border-color : black;
    border-style : solid;
    display: block;
    margin-right : auto;
    margin-left : auto;
}

div {
    text-align : center;
}

</style>
<div>
<img src="{{ absolute_url(asset('build/img/unnamed.jpg')) }}" alt="">
<br>
<b>Hauteur max : <i>Une valeur </i></b>
<br>
<b>Hauteur min : <i>Une valeur </i></b>
<br>
<b>...</b>
</div>